name: SnowDawn
version: '1.0-SNAPSHOT'
main: com.github.bea4dev.snowDawn.SnowDawn
api-version: '1.21'
load: STARTUP
dependencies:
  server:
    VanillaSource:
      load: BEFORE
      required: true

libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.20.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.20.0